### ISSUE TITLE
TRAM not working

### ISSUE THREAD

**Issue by reutmenashe** [mitre-attack/tram#44]
I installed and run the TRAM from your GitHub
But when sending a URL for analyzing and scanning
I didn’t get any responds, where one can check the logs/debugging of the system?
No notifications of what’s going on the system itself and I didn’t find any logs on the Tram installation path.

ENV:
Ptyhon3, Ubuntu on windows
The URL send to scan: https://unit42.paloaltonetworks.com/autoit-compiled-malware/

**Comment by sarahyoder** [comment]
If i understand your problem correctly, you were able to install the program without problems, but nothing happens when you submit the URL? Two things come to mind: the first is to double check there is data in the database, if there is not, then there is no data for TRAM to compare to; next, how long did you wait after the report was submitted? I would suggest trying again, and give it about 2 minutes as it can take a while to process.

**Comment by reutmenashe** [comment]
so:
first, yes, you understand it correct: installed without problems and nothing happens when submitting url.
1. not sure how to check if there is data in the database, how am i suppose to add data to this ? like this the ls of the path, and the ls of the 'database' path:
```
~/temp/tram (master)
$ ls
conf/            database/  models/     README.md         service/  webapp/
CONTRIBUTING.md  handlers/  NOTICE.txt  requirements.txt  tram.py

```
```
~/temp/tram/database (master)
$ ls
dao.py  tram_relation.py

```
2. i wait much more then 2 minutes, even hours so :-)

**Comment by sarahyoder** [comment]
Double check the database, since I have ran into that issue myself: 
https://github.com/mitre-attack/tram/wiki/Common-Problems

If data is there, I would check the command line when the URL is submitted to see if any additional information is given, or try installing on the base Windows system as it has not been tested in Ubuntu at this time.
